# Generated by Django 5.1.6 on 2025-02-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_account_groups_alter_account_user_permissions'),
        ('user', '0006_remove_account_username_alter_account_email'),
    ]

    operations = [
    ]
