# Generated by Django 5.1.3 on 2025-02-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('niveau_d_etude', models.CharField(max_length=30)),
                ('specialite', models.CharField(max_length=30)),
                ('cv_ou_attestation', models.FileField(blank=True, null=True, upload_to='dossier/')),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise_ou_recruteur', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField()),
                ('domaine_ou_services', models.TextField(blank=True, null=True)),
                ('situation_geographique', models.CharField(max_length=128)),
                ('coordonne_localisation', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
