# Generated by Django 5.1.3 on 2025-02-01 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_candidat_recruteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='recruteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offers.recruteur'),
            preserve_default=False,
        ),
    ]
