# Generated by Django 5.1.3 on 2025-02-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offre_recruteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offre')),
            ],
        ),
    ]
