# Generated by Django 5.1.3 on 2025-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_candidat_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='type_de_contrat',
            field=models.CharField(choices=[('STAGE', 'Stage'), ('CDD', 'CDD'), ('CDI', 'CDI')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postoffre',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
