# Generated by Django 5.1.3 on 2025-02-01 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offre_type_de_contrat_postoffre_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoffre',
            name='deja_poste',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postoffre',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='postoffre',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='En cours', max_length=10),
        ),
    ]
