# Generated by Django 5.1.3 on 2025-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_postoffre_deja_poste_alter_postoffre_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='type_de_contrat',
            field=models.CharField(choices=[('FREELANCE', 'Freelance'), ('STAGE', 'Stage'), ('CDD', 'CDD'), ('CDI', 'CDI')], max_length=10),
        ),
    ]
