# Generated by Django 5.1.3 on 2025-02-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_offre_type_de_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
