# Generated by Django 5.1.3 on 2025-02-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteur',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
