# Generated by Django 5.1.3 on 2025-02-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_candidat_user_recruteur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='tel',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
